const watchtowerSources = [{"name":"Anikoto","lang":"en","baseUrl":"https://anikoto.to","iconUrl":"https://anikoto.to/favicon.ico","typeSource":"single","itemType":1,"version":"1.0.0","pkgPath":"anime/src/en/anikoto.js","notes":"Anikoto — anime streaming HD gratuit"}];
const BASE_URL = "https://anikoto.to";
class DefaultExtension extends MProvider {
    constructor() { super(); }
    getHeaders() { return {"User-Agent":"Mozilla/5.0","Referer":`${BASE_URL}/`}; }
    parseList(h) { const l=[];const re=/<a[^>]+href="([^"]+)"[\s\S]*?<img[^>]+(?:src|data-src)="([^"]+)"[\s\S]*?<\/a>[\s\S]*?<h2[^>]*>([^<]+)<\/h2>/g;let m;const s={};while((m=re.exec(h))!==null){if(!s[m[1]]){s[m[1]]=1;l.push({link:m[1],imageUrl:m[2],name:m[3].trim()});}}if(l.length===0){const r2=/href="([^"]+)"[\s\S]*?src="([^"]+)"[\s\S]*?alt="([^"]*)"/g;while((m=r2.exec(h))!==null){if(!s[m[1]]&&m[3].trim()&&!m[3].toLowerCase().includes("logo")){s[m[1]]=1;l.push({link:m[1],imageUrl:m[2],name:m[3].trim()});}}}return l; }
    async getPopular(p) { const r=await new Client().get(`${BASE_URL}/popular?page=${p}`,this.getHeaders());return{list:this.parseList(r.body),hasNextPage:r.body.includes('page=')}; }
    async getLatestUpdates(p) { const r=await new Client().get(`${BASE_URL}/recently-updated?page=${p}`,this.getHeaders());return{list:this.parseList(r.body),hasNextPage:r.body.includes('page=')}; }
    async search(q,p) { if(!q)return this.getPopular(p);const r=await new Client().get(`${BASE_URL}/search?keyword=${encodeURIComponent(q)}&page=${p}`,this.getHeaders());return{list:this.parseList(r.body),hasNextPage:false}; }
    async getDetail(url) { const u=url.startsWith("http")?url:`${BASE_URL}${url}`;const r=await new Client().get(u,this.getHeaders());const h=r.body;const nm=h.match(/<h1[^>]*>([^<]+)<\/h1>/);const n=nm?nm[1].trim():"";const dm=h.match(/<div[^>]*class="[^"]*description[^"]*"[^>]*>([\s\S]*?)<\/div>/);const d=dm?dm[1].replace(/<[^>]+>/g,"").trim():"";const im=h.match(/<img[^>]+src="([^"]+)"[^>]*(?:poster|cover)/i);const img=im?im[1]:"";const ep=[];const er=/href="([^"]*episode[^"]*)"[^>]*>([^<]+)<\/a>/g;let em;while((em=er.exec(h))!==null){ep.push({name:em[2].trim(),url:em[1]});}return{name:n,description:d,imageUrl:img,genres:[],status:0,chapters:ep}; }
    async getVideoList(url) { const u=url.startsWith("http")?url:`${BASE_URL}${url}`;const r=await new Client().get(u,this.getHeaders());const h=r.body;const v=[];const re=/(?:data-src|src)="(https?:\/\/[^"]+(?:embed|player|stream|m3u8)[^"]*)"/g;let m;while((m=re.exec(h))!==null){v.push({url:m[1],quality:"Auto",originalUrl:m[1]});}return v; }
    getFilterList() { return []; } getSourcePreferences() { return []; }
}
